#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftMotor,     tmotorTetrix, openLoop, driveLeft)
#pragma config(Motor,  mtr_S1_C1_2,     rightMotor,    tmotorTetrix, openLoop, reversed, driveRight)
#pragma config(Motor,  mtr_S1_C2_1,     armMotor,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     elbowMotor,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    rHand,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    lHand,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
#pragma config(SrvoPosition,  Position01,            126, 126, 128, 128, 128, 128, 128, 128)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int armMotorHold();
int elbowMotorHold();
void grab();
void release();
void jolt();
void auto();

float error = 0, error2 = 0, threshold3 = 10;

task main()
{
	int threshold = 10, threshold1 = 100, threshold2 = -100;
	bFloatDuringInactiveMotorPWM = false;
	grab();
	auto();
	while(true)
	{
		getJoystickSettings(joystick);

		int power1 = -1*joystick.joy1_y1, power2 = -1*joystick.joy1_y2;

		getJoystickSettings(joystick);
		if(abs(joystick.joy1_y1) > threshold && abs(joystick.joy1_y1) < threshold1)
		{
			motor[leftMotor] = power1;
			getJoystickSettings(joystick);
		}
		else if (abs(joystick.joy1_y1) > threshold && joystick.joy1_y1 > threshold1)
		{
			motor[leftMotor] = -100;
			getJoystickSettings(joystick);
		}
		else if (abs(joystick.joy1_y1) > threshold && joystick.joy1_y1 < threshold2)
		{
			motor[leftMotor] = 100;
			getJoystickSettings(joystick);
		}
		else if(joy1Btn(05) == 1)
		{
			motor[leftMotor] = 0;
			getJoystickSettings(joystick);
		}
		else if(joy1Btn(06) == 1)
		{
			motor[leftMotor] = 100;
			getJoystickSettings(joystick);
		}
		else
			motor[leftMotor] = 0;
		getJoystickSettings(joystick);
		if(abs(joystick.joy1_y2) > threshold && abs(joystick.joy1_y2) < threshold1)
		{
			motor[rightMotor] = power2;
			getJoystickSettings(joystick);
		}
		else if (abs(joystick.joy1_y2) > threshold && joystick.joy1_y2 > threshold1)
		{
			motor[rightMotor] = -100;
			getJoystickSettings(joystick);
		}
		else if (abs(joystick.joy1_y2) > threshold && joystick.joy1_y2 < threshold2)
		{
			motor[rightMotor] = 100;
			getJoystickSettings(joystick);
		}
		else if(joy1Btn(05) == 1)
		{
			motor[rightMotor] = 100;
			getJoystickSettings(joystick);
		}
		else if(joy1Btn(06) == 1)
		{
			motor[rightMotor] = 0;
			getJoystickSettings(joystick);
		}
		else
			motor[rightMotor] = 0;
		getJoystickSettings(joystick);
		if(joystick.joy1_TopHat == 0)
		{
			motor[armMotor] = 37;
			nMotorEncoder[armMotor] = 0;
			getJoystickSettings(joystick);
		}
		else if(joystick.joy1_TopHat == 4)
		{
			motor[armMotor] = -5;
			nMotorEncoder[armMotor] = 0;
			getJoystickSettings(joystick);
		}
		else if(joy1Btn(2) == 1)
		{
			jolt();
			nMotorEncoder[armMotor] = 0;
			getJoystickSettings(joystick);
		}
		else
			motor[armMotor] = armMotorHold();
		getJoystickSettings(joystick);
		if(joystick.joy1_TopHat == 2)
		{
			motor[elbowMotor] = 65;
			nMotorEncoder[elbowMotor] = 0;
			getJoystickSettings(joystick);
		}
		else if(joystick.joy1_TopHat == 6)
		{
			motor[elbowMotor] = 5;
			nMotorEncoder[elbowMotor] = 0;
			getJoystickSettings(joystick);
		}
		else
			motor[elbowMotor] = elbowMotorHold();
		getJoystickSettings(joystick);
		if(joy1Btn(1) == 1)
		{
			grab();
			getJoystickSettings(joystick);
		}
		else if(joy1Btn(3) == 1)
		{
			release();
			getJoystickSettings(joystick);
		}
		else
		{
			servo[rHand] = ServoValue[rHand];
			servo[lHand] = ServoValue[lHand];
			getJoystickSettings(joystick);
		}
		getJoystickSettings(joystick);
	}
}

int armMotorHold()
{
	float armPower, lastError, Kp = 0.65, Kd = 0.15, runTime = 0;
	error = 0 - nMotorEncoder[armMotor];
	if (fabs(error) < threshold3)
		lastError = 0;
	if(runTime == 0)
	{
		lastError = 0;
		runTime++;
	}
	armPower = Kp*error + Kd*(error - lastError);
	if(armPower > 100)
		armPower = 100;
	else if(armPower < -100)
		armPower = -100;
	lastError = error;
	return armPower;
}

int elbowMotorHold()
{
	float elbowPower, lastError2, Kp = 0.55, Kd = 0.05, runTime2 = 0;
	error2 = 0 - nMotorEncoder[elbowMotor];
	if (fabs(error2) < threshold3)
		lastError2 = 0;
	if(runTime2 == 0)
	{
		lastError2 = 0;
		runTime2++;
	}
	elbowPower = Kp*error2 + Kd*(error2 - lastError2);
	if(elbowPower > 100)
		elbowPower = 100;
	else if(elbowPower < -100)
		elbowPower = -100;
	lastError2 = error2;
	return elbowPower;
}

void grab()
{
	servo[rHand] = 145;
	servo[lHand] = 185;
	wait1Msec(1000);
}

void release()
{
	servo[rHand] = 220;
	servo[lHand] = 100;
	wait1Msec(1000);
}

void jolt()
{
	motor[armMotor] = -37;
	wait1Msec(1000);
	motor[armMotor] = 0;
	nMotorEncoder[armMotor] = 0;
}

void auto()
{
	motor[rightMotor] = -100;
	motor[leftMotor] = -100;
	wait1Msec(5500);
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
	wait1Msec(50);
	motor[rightMotor] = 0;
	motor[leftMotor] = -100;
	wait1Msec(1600);
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
	wait1Msec(50);
	motor[rightMotor] = -100;
	motor[leftMotor] = -100;
	wait1Msec(3850);
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
}
